# Generated by Django 3.2.2 on 2021-05-14 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=14)),
                ('License_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Number', models.CharField(max_length=14)),
                ('Owner', models.CharField(max_length=14)),
                ('RC_number', models.CharField(max_length=14)),
                ('PAN_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10, message='Invalid PAN Number')])),
                ('Capacity', models.FloatField()),
                ('Insurance_policy_number', models.CharField(max_length=14)),
                ('Insurance_expiry_date', models.DateField()),
                ('Safety_equipments', models.BooleanField(default=False)),
                ('GPS', models.BooleanField(default=False)),
                ('Contact_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid Contact Number')])),
            ],
        ),
        migrations.CreateModel(
            name='Trip_details',
            fields=[
                ('Trip_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=14)),
                ('Total_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Advance_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.driver')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.vehicle')),
            ],
        ),
    ]
