# Generated by Django 3.2.2 on 2021-06-01 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name="Driver's Name")),
                ('License_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15, message='Invalid License Number')], verbose_name='DL Number')),
                ('License_expiry', models.DateField(validators=[logistics.models.date_validate], verbose_name='License Expiry')),
                ('Contact_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid Contact Number')], verbose_name='Contact Number')),
                ('License_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=50, verbose_name="Owner's Name")),
                ('RC_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(12, message='Invalid RC Number'), django.core.validators.RegexValidator('([A-Z]{2})+-([0-9]{1})+-[A-Z]+-[0-9]{4}', message='Use proper formatting')], verbose_name='RC Number')),
                ('PAN_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid PAN Number')], verbose_name='PAN Number')),
                ('Type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('19FT', '19FT'), ('22FT', '22FT'), ('32FT S', '32FT S'), ('32FT M', '32FT M'), ('OTHER', 'OTHER')], default='PICKUP', max_length=10, verbose_name='Type of Vehicle')),
                ('Other', models.CharField(blank=True, max_length=10, verbose_name='')),
                ('Insurance_policy_number', models.CharField(max_length=25)),
                ('PUC_expiry_date', models.DateField()),
                ('Insurance_expiry_date', models.DateField(validators=[logistics.models.date_validate])),
                ('Safety_equipments', models.BooleanField(default=False)),
                ('GPS', models.BooleanField(default=False)),
                ('Contact_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid Contact Number'), django.core.validators.RegexValidator('([0-9]{10})', message='Should be numeric values only')])),
                ('Notifications', models.BooleanField(default=True, verbose_name='Notifications Needed')),
                ('Insurance_expired', models.BooleanField(default=False)),
                ('PUC_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_id', models.CharField(max_length=14)),
                ('Source', models.CharField(max_length=14)),
                ('Total_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Advance_payment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Date_created', models.DateField(auto_now_add=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.driver', verbose_name="Driver's Name")),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.vehicle', verbose_name='RC Number')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='Vehicle',
            field=models.ManyToManyField(to='logistics.Vehicle'),
        ),
        migrations.CreateModel(
            name='Bank_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=20, verbose_name='Account Number')),
                ('Account_holder', models.CharField(max_length=20, verbose_name='Account Holder')),
                ('IFSC', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('Account_type', models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT')], default='CURRENT', max_length=7, verbose_name='Account Type')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.vehicle', verbose_name='RC Number')),
            ],
        ),
    ]
