# Generated by Django 3.2.2 on 2021-05-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip_details',
            new_name='Trip_detail',
        ),
    ]
