# Generated by Django 3.2.2 on 2021-06-11 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_detail',
            name='Other_charges',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other Charges'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Distance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance (Kms)'),
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Rate_type',
            field=models.CharField(choices=[('FIX', 'FIX'), ('VARIABLE', 'VARIABLE')], max_length=8, verbose_name='Rate Type'),
        ),
    ]
