# Generated by Django 3.2.2 on 2021-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Insurance_expired',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Notifications',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='PUC_expired',
        ),
    ]
