# Generated by Django 3.2.2 on 2021-05-23 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_detail',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
