# Generated by Django 3.2.2 on 2021-06-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Details',
            field=models.CharField(max_length=50, verbose_name='Detail'),
        ),
    ]
