# Generated by Django 3.2.2 on 2021-05-17 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_trip_details_trip_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='License_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10, message='Invalid RC Number')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='PAN_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid PAN Number')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='RC_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10, message='Invalid RC Number')]),
        ),
    ]
