# Generated by Django 3.2.2 on 2021-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_vehicle_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Insurance_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='PUC_expired',
            field=models.BooleanField(default=False),
        ),
    ]
