# Generated by Django 3.2.2 on 2021-06-22 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_transaction_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_detail',
            name='Rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
