# Generated by Django 3.2.2 on 2021-05-19 04:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20210517_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=20, verbose_name='Account Number')),
                ('Account_holder', models.CharField(max_length=20, verbose_name='Account Holder')),
                ('Ifsc', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('Account_type', models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT')], default='CURRENT', max_length=7, verbose_name='Account Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='Number',
        ),
        migrations.AddField(
            model_name='driver',
            name='Contact_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid Contact Number')]),
        ),
        migrations.AddField(
            model_name='driver',
            name='License_expiry',
            field=models.DateField(default=django.utils.timezone.now, validators=[logistics.models.date_validate]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Other',
            field=models.CharField(default=None, help_text='If Selected Other', max_length=10, verbose_name=' '),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Type',
            field=models.CharField(choices=[('PICKUP', 'PICKUP'), ('19FT', 'PICKUP'), ('PICKUP', 'PICKUP'), ('PICKUP', 'PICKUP'), ('PICKUP', 'PICKUP')], default='PICKUP', max_length=10, verbose_name='Type of Vehicle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='License_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15, message='Invalid License Number')], verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Name',
            field=models.CharField(max_length=14, verbose_name="Driver's Name"),
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.driver', verbose_name="Driver's Name"),
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='logistics.vehicle', verbose_name='RC Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Insurance_expiry_date',
            field=models.DateField(validators=[logistics.models.date_validate]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Owner',
            field=models.CharField(max_length=14, verbose_name="Owner's Name"),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='PAN_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid PAN Number')], verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='RC_number',
            field=models.CharField(help_text='GJ-XX-AB-XXXX', max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12, message='Invalid RC Number')], verbose_name='RC Number'),
        ),
    ]
