# Generated by Django 3.2.2 on 2021-06-04 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20210601_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='Contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', message='Invalid Number')], verbose_name='Contact Number'),
        ),
    ]
