# Generated by Django 3.2.2 on 2021-06-22 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_trip_detail_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_detail',
            name='Rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
