# Generated by Django 3.2.2 on 2021-05-20 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_auto_20210519_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_detail',
            old_name='Ifsc',
            new_name='IFSC',
        ),
        migrations.AddField(
            model_name='bank_detail',
            name='Vehicle',
            field=models.ForeignKey(default=5834, on_delete=django.db.models.deletion.RESTRICT, to='logistics.vehicle', verbose_name='RC Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='Contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Invalid Contact Number')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='License_expiry',
            field=models.DateField(validators=[logistics.models.date_validate], verbose_name='License Expiry'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='License_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15, message='Invalid License Number')], verbose_name='DL Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Other',
            field=models.CharField(default=None, max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='RC_number',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12, message='Invalid RC Number')], verbose_name='RC Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Type',
            field=models.CharField(choices=[('PICKUP', 'PICKUP'), ('19FT', '19FT'), ('22FT', '22FT'), ('32FT S', '32FT S'), ('32FT M', '32FT M'), ('OTHER', 'OTHER')], default='PICKUP', max_length=10, verbose_name='Type of Vehicle'),
        ),
    ]
