# Generated by Django 3.2.2 on 2021-06-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20210604_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
