# Generated by Django 3.2.2 on 2021-07-08 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_trip_detail_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_detail',
            name='Distance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distance(Kms)'),
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trip_detail',
            name='Trip_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
